# Generated by Django 5.1.3 on 2024-11-20 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='title',
            new_name='task',
        ),
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
    ]
